export const imageIcons = {
  food: require('../../assets/images/generated/food.png'),
  water: require('../../assets/images/generated/water.png'),
  medicine: require('../../assets/images/generated/medicine.png'),
  babySupplies: require('../../assets/images/generated/babySupplies.png'),
  hygiene: require('../../assets/images/generated/hygiene.png'),
  clothing: require('../../assets/images/generated/clothing.png'),
  flashlight: require('../../assets/images/generated/flashlight.png'),
  landslide: require('../../assets/images/generated/landslide.png'),
  damage: require('../../assets/images/generated/damage.png'),
  stranded: require('../../assets/images/generated/stranded.png'),
  powerline: require('../../assets/images/generated/powerline.png'),
  supplies: require('../../assets/images/generated/supplies.png'),
  home: require('../../assets/images/home-not-active.png'),
  homeActive: require('../../assets/images/home-active.png'),
  reportActive: require('../../assets/images/report-active.png'),
  statusActive: require('../../assets/images/status-active.png'),
  resident: require('../../assets/images/resident.png'),
  volunteer: require('../../assets/images/volunteer.png'),
  elderly: require('../../assets/images/elderly.png'),
  baby: require('../../assets/images/baby.png'),
  disability: require('../../assets/images/person-with-disability.png'),
  pregnant: require('../../assets/images/pregnant.png'),
  noFlooding: require('../../assets/images/no-flooding.png'),
  ankleDeep: require('../../assets/images/ankle-deep.png'),
  kneeDeep: require('../../assets/images/knee-deep.png'),
  waistDeep: require('../../assets/images/waist-deep-or-higher.png'),
  roadPassable: require('../../assets/images/road-is-passable.png'),
  boat: require('../../assets/images/flooded-use-boat.png'),
  airRescue: require('../../assets/images/need-air-rescue.png'),
  unknown: require('../../assets/images/unknown.png'),
  report: require('../../assets/images/report-not-active.png'),
  status: require('../../assets/images/status-not-active.png'),
};

export const supplyImageIcons = {
  needs_food: imageIcons.food,
  needs_water: imageIcons.water,
  needs_medicine: imageIcons.medicine,
  needs_baby_supplies: imageIcons.babySupplies,
  needs_hygiene: imageIcons.hygiene,
  needs_clothing_blankets: imageIcons.clothing,
  needs_power_light: imageIcons.flashlight,
};
